/**
 * RESTful PTV
 * Restful way to use Palvelutietovaranto.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.otavanopisto.restfulptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import fi.otavanopisto.restfulptv.client.model.FintoItem;
import fi.otavanopisto.restfulptv.client.model.LanguageItem;
import fi.otavanopisto.restfulptv.client.model.LocalizedListItem;
import fi.otavanopisto.restfulptv.client.model.WebPage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
/**
 * Service
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-03T15:30:31.843+03:00")
public class Service   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("statutoryDescriptionId")
  private String statutoryDescriptionId = null;

  @JsonProperty("serviceClasses")
  private List<FintoItem> serviceClasses = new ArrayList<FintoItem>();

  @JsonProperty("ontologyTerms")
  private List<FintoItem> ontologyTerms = new ArrayList<FintoItem>();

  @JsonProperty("targetGroups")
  private List<FintoItem> targetGroups = new ArrayList<FintoItem>();

  @JsonProperty("lifeEvents")
  private List<FintoItem> lifeEvents = new ArrayList<FintoItem>();

  @JsonProperty("industrialClasses")
  private List<FintoItem> industrialClasses = new ArrayList<FintoItem>();

  @JsonProperty("serviceNames")
  private List<LocalizedListItem> serviceNames = new ArrayList<LocalizedListItem>();

  @JsonProperty("serviceDescriptions")
  private List<LocalizedListItem> serviceDescriptions = new ArrayList<LocalizedListItem>();

  @JsonProperty("languages")
  private List<String> languages = new ArrayList<String>();

  @JsonProperty("keywords")
  private List<String> keywords = new ArrayList<String>();

  @JsonProperty("serviceCoverageType")
  private String serviceCoverageType = null;

  @JsonProperty("municipalities")
  private List<String> municipalities = new ArrayList<String>();

  @JsonProperty("webPages")
  private List<WebPage> webPages = new ArrayList<WebPage>();

  @JsonProperty("requirements")
  private List<LanguageItem> requirements = new ArrayList<LanguageItem>();

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("serviceChargeType")
  private String serviceChargeType = null;

  @JsonProperty("serviceAdditionalInformations")
  private List<LocalizedListItem> serviceAdditionalInformations = new ArrayList<LocalizedListItem>();

  public Service id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Service type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Service statutoryDescriptionId(String statutoryDescriptionId) {
    this.statutoryDescriptionId = statutoryDescriptionId;
    return this;
  }

   /**
   * Get statutoryDescriptionId
   * @return statutoryDescriptionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatutoryDescriptionId() {
    return statutoryDescriptionId;
  }

  public void setStatutoryDescriptionId(String statutoryDescriptionId) {
    this.statutoryDescriptionId = statutoryDescriptionId;
  }

  public Service serviceClasses(List<FintoItem> serviceClasses) {
    this.serviceClasses = serviceClasses;
    return this;
  }

  public Service addServiceClassesItem(FintoItem serviceClassesItem) {
    this.serviceClasses.add(serviceClassesItem);
    return this;
  }

   /**
   * Get serviceClasses
   * @return serviceClasses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getServiceClasses() {
    return serviceClasses;
  }

  public void setServiceClasses(List<FintoItem> serviceClasses) {
    this.serviceClasses = serviceClasses;
  }

  public Service ontologyTerms(List<FintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
    return this;
  }

  public Service addOntologyTermsItem(FintoItem ontologyTermsItem) {
    this.ontologyTerms.add(ontologyTermsItem);
    return this;
  }

   /**
   * Get ontologyTerms
   * @return ontologyTerms
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getOntologyTerms() {
    return ontologyTerms;
  }

  public void setOntologyTerms(List<FintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
  }

  public Service targetGroups(List<FintoItem> targetGroups) {
    this.targetGroups = targetGroups;
    return this;
  }

  public Service addTargetGroupsItem(FintoItem targetGroupsItem) {
    this.targetGroups.add(targetGroupsItem);
    return this;
  }

   /**
   * Get targetGroups
   * @return targetGroups
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getTargetGroups() {
    return targetGroups;
  }

  public void setTargetGroups(List<FintoItem> targetGroups) {
    this.targetGroups = targetGroups;
  }

  public Service lifeEvents(List<FintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
    return this;
  }

  public Service addLifeEventsItem(FintoItem lifeEventsItem) {
    this.lifeEvents.add(lifeEventsItem);
    return this;
  }

   /**
   * Get lifeEvents
   * @return lifeEvents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getLifeEvents() {
    return lifeEvents;
  }

  public void setLifeEvents(List<FintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
  }

  public Service industrialClasses(List<FintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
    return this;
  }

  public Service addIndustrialClassesItem(FintoItem industrialClassesItem) {
    this.industrialClasses.add(industrialClassesItem);
    return this;
  }

   /**
   * Get industrialClasses
   * @return industrialClasses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getIndustrialClasses() {
    return industrialClasses;
  }

  public void setIndustrialClasses(List<FintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
  }

  public Service serviceNames(List<LocalizedListItem> serviceNames) {
    this.serviceNames = serviceNames;
    return this;
  }

  public Service addServiceNamesItem(LocalizedListItem serviceNamesItem) {
    this.serviceNames.add(serviceNamesItem);
    return this;
  }

   /**
   * Get serviceNames
   * @return serviceNames
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getServiceNames() {
    return serviceNames;
  }

  public void setServiceNames(List<LocalizedListItem> serviceNames) {
    this.serviceNames = serviceNames;
  }

  public Service serviceDescriptions(List<LocalizedListItem> serviceDescriptions) {
    this.serviceDescriptions = serviceDescriptions;
    return this;
  }

  public Service addServiceDescriptionsItem(LocalizedListItem serviceDescriptionsItem) {
    this.serviceDescriptions.add(serviceDescriptionsItem);
    return this;
  }

   /**
   * Get serviceDescriptions
   * @return serviceDescriptions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getServiceDescriptions() {
    return serviceDescriptions;
  }

  public void setServiceDescriptions(List<LocalizedListItem> serviceDescriptions) {
    this.serviceDescriptions = serviceDescriptions;
  }

  public Service languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public Service addLanguagesItem(String languagesItem) {
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public Service keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public Service addKeywordsItem(String keywordsItem) {
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public Service serviceCoverageType(String serviceCoverageType) {
    this.serviceCoverageType = serviceCoverageType;
    return this;
  }

   /**
   * Get serviceCoverageType
   * @return serviceCoverageType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getServiceCoverageType() {
    return serviceCoverageType;
  }

  public void setServiceCoverageType(String serviceCoverageType) {
    this.serviceCoverageType = serviceCoverageType;
  }

  public Service municipalities(List<String> municipalities) {
    this.municipalities = municipalities;
    return this;
  }

  public Service addMunicipalitiesItem(String municipalitiesItem) {
    this.municipalities.add(municipalitiesItem);
    return this;
  }

   /**
   * Get municipalities
   * @return municipalities
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getMunicipalities() {
    return municipalities;
  }

  public void setMunicipalities(List<String> municipalities) {
    this.municipalities = municipalities;
  }

  public Service webPages(List<WebPage> webPages) {
    this.webPages = webPages;
    return this;
  }

  public Service addWebPagesItem(WebPage webPagesItem) {
    this.webPages.add(webPagesItem);
    return this;
  }

   /**
   * Get webPages
   * @return webPages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<WebPage> getWebPages() {
    return webPages;
  }

  public void setWebPages(List<WebPage> webPages) {
    this.webPages = webPages;
  }

  public Service requirements(List<LanguageItem> requirements) {
    this.requirements = requirements;
    return this;
  }

  public Service addRequirementsItem(LanguageItem requirementsItem) {
    this.requirements.add(requirementsItem);
    return this;
  }

   /**
   * Get requirements
   * @return requirements
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LanguageItem> getRequirements() {
    return requirements;
  }

  public void setRequirements(List<LanguageItem> requirements) {
    this.requirements = requirements;
  }

  public Service publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Get publishingStatus
   * @return publishingStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public Service serviceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
    return this;
  }

   /**
   * Get serviceChargeType
   * @return serviceChargeType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getServiceChargeType() {
    return serviceChargeType;
  }

  public void setServiceChargeType(String serviceChargeType) {
    this.serviceChargeType = serviceChargeType;
  }

  public Service serviceAdditionalInformations(List<LocalizedListItem> serviceAdditionalInformations) {
    this.serviceAdditionalInformations = serviceAdditionalInformations;
    return this;
  }

  public Service addServiceAdditionalInformationsItem(LocalizedListItem serviceAdditionalInformationsItem) {
    this.serviceAdditionalInformations.add(serviceAdditionalInformationsItem);
    return this;
  }

   /**
   * Get serviceAdditionalInformations
   * @return serviceAdditionalInformations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getServiceAdditionalInformations() {
    return serviceAdditionalInformations;
  }

  public void setServiceAdditionalInformations(List<LocalizedListItem> serviceAdditionalInformations) {
    this.serviceAdditionalInformations = serviceAdditionalInformations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.id, service.id) &&
        Objects.equals(this.type, service.type) &&
        Objects.equals(this.statutoryDescriptionId, service.statutoryDescriptionId) &&
        Objects.equals(this.serviceClasses, service.serviceClasses) &&
        Objects.equals(this.ontologyTerms, service.ontologyTerms) &&
        Objects.equals(this.targetGroups, service.targetGroups) &&
        Objects.equals(this.lifeEvents, service.lifeEvents) &&
        Objects.equals(this.industrialClasses, service.industrialClasses) &&
        Objects.equals(this.serviceNames, service.serviceNames) &&
        Objects.equals(this.serviceDescriptions, service.serviceDescriptions) &&
        Objects.equals(this.languages, service.languages) &&
        Objects.equals(this.keywords, service.keywords) &&
        Objects.equals(this.serviceCoverageType, service.serviceCoverageType) &&
        Objects.equals(this.municipalities, service.municipalities) &&
        Objects.equals(this.webPages, service.webPages) &&
        Objects.equals(this.requirements, service.requirements) &&
        Objects.equals(this.publishingStatus, service.publishingStatus) &&
        Objects.equals(this.serviceChargeType, service.serviceChargeType) &&
        Objects.equals(this.serviceAdditionalInformations, service.serviceAdditionalInformations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, statutoryDescriptionId, serviceClasses, ontologyTerms, targetGroups, lifeEvents, industrialClasses, serviceNames, serviceDescriptions, languages, keywords, serviceCoverageType, municipalities, webPages, requirements, publishingStatus, serviceChargeType, serviceAdditionalInformations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    statutoryDescriptionId: ").append(toIndentedString(statutoryDescriptionId)).append("\n");
    sb.append("    serviceClasses: ").append(toIndentedString(serviceClasses)).append("\n");
    sb.append("    ontologyTerms: ").append(toIndentedString(ontologyTerms)).append("\n");
    sb.append("    targetGroups: ").append(toIndentedString(targetGroups)).append("\n");
    sb.append("    lifeEvents: ").append(toIndentedString(lifeEvents)).append("\n");
    sb.append("    industrialClasses: ").append(toIndentedString(industrialClasses)).append("\n");
    sb.append("    serviceNames: ").append(toIndentedString(serviceNames)).append("\n");
    sb.append("    serviceDescriptions: ").append(toIndentedString(serviceDescriptions)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    serviceCoverageType: ").append(toIndentedString(serviceCoverageType)).append("\n");
    sb.append("    municipalities: ").append(toIndentedString(municipalities)).append("\n");
    sb.append("    webPages: ").append(toIndentedString(webPages)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    serviceChargeType: ").append(toIndentedString(serviceChargeType)).append("\n");
    sb.append("    serviceAdditionalInformations: ").append(toIndentedString(serviceAdditionalInformations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

