/**
 * RESTful PTV
 * Restful way to use Palvelutietovaranto.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.metatavu.restfulptv.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import fi.metatavu.restfulptv.client.model.FintoItem;
import fi.metatavu.restfulptv.client.model.LanguageItem;
import fi.metatavu.restfulptv.client.model.Law;
import fi.metatavu.restfulptv.client.model.LocalizedListItem;
import fi.metatavu.restfulptv.client.model.Municipality;
import fi.metatavu.restfulptv.client.model.ServiceOrganization;
import fi.metatavu.restfulptv.client.model.ServiceServiceChannel;
import fi.metatavu.restfulptv.client.model.WebPage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
/**
 * Service
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-10T22:00:56.420+03:00")
public class Service   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("statutoryDescriptionId")
  private String statutoryDescriptionId = null;

  @JsonProperty("serviceClasses")
  private List<FintoItem> serviceClasses = new ArrayList<FintoItem>();

  @JsonProperty("ontologyTerms")
  private List<FintoItem> ontologyTerms = new ArrayList<FintoItem>();

  @JsonProperty("targetGroups")
  private List<FintoItem> targetGroups = new ArrayList<FintoItem>();

  @JsonProperty("lifeEvents")
  private List<FintoItem> lifeEvents = new ArrayList<FintoItem>();

  @JsonProperty("industrialClasses")
  private List<FintoItem> industrialClasses = new ArrayList<FintoItem>();

  @JsonProperty("names")
  private List<LocalizedListItem> names = new ArrayList<LocalizedListItem>();

  @JsonProperty("descriptions")
  private List<LocalizedListItem> descriptions = new ArrayList<LocalizedListItem>();

  @JsonProperty("languages")
  private List<String> languages = new ArrayList<String>();

  @JsonProperty("keywords")
  private List<LanguageItem> keywords = new ArrayList<LanguageItem>();

  @JsonProperty("legislation")
  private List<Law> legislation = new ArrayList<Law>();

  @JsonProperty("coverageType")
  private String coverageType = null;

  @JsonProperty("municipalities")
  private List<Municipality> municipalities = new ArrayList<Municipality>();

  @JsonProperty("webPages")
  private List<WebPage> webPages = new ArrayList<WebPage>();

  @JsonProperty("requirements")
  private List<LanguageItem> requirements = new ArrayList<LanguageItem>();

  @JsonProperty("publishingStatus")
  private String publishingStatus = null;

  @JsonProperty("chargeType")
  private String chargeType = null;

  @JsonProperty("additionalInformations")
  private List<LocalizedListItem> additionalInformations = new ArrayList<LocalizedListItem>();

  @JsonProperty("organizations")
  private List<ServiceOrganization> organizations = new ArrayList<ServiceOrganization>();

  @JsonProperty("electronicServiceChannels")
  private List<ServiceServiceChannel> electronicServiceChannels = new ArrayList<ServiceServiceChannel>();

  @JsonProperty("phoneServiceChannels")
  private List<ServiceServiceChannel> phoneServiceChannels = new ArrayList<ServiceServiceChannel>();

  @JsonProperty("printableFormServiceChannels")
  private List<ServiceServiceChannel> printableFormServiceChannels = new ArrayList<ServiceServiceChannel>();

  @JsonProperty("serviceLocationServiceChannels")
  private List<ServiceServiceChannel> serviceLocationServiceChannels = new ArrayList<ServiceServiceChannel>();

  @JsonProperty("webPageServiceChannels")
  private List<ServiceServiceChannel> webPageServiceChannels = new ArrayList<ServiceServiceChannel>();

  public Service id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Service type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Service type. Possible values are: Service or PermissionAndObligation.  NOTE! Current PTV database does not anymore support for types Notice, Registration or Permission - they are automatically mapped into PermissionAndObligation type when possible.  POST and PUT methods accepts old types but GET method only can return Service or PermissionAndObligation types.
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "Service type. Possible values are: Service or PermissionAndObligation.  NOTE! Current PTV database does not anymore support for types Notice, Registration or Permission - they are automatically mapped into PermissionAndObligation type when possible.  POST and PUT methods accepts old types but GET method only can return Service or PermissionAndObligation types.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Service statutoryDescriptionId(String statutoryDescriptionId) {
    this.statutoryDescriptionId = statutoryDescriptionId;
    return this;
  }

   /**
   * Get statutoryDescriptionId
   * @return statutoryDescriptionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatutoryDescriptionId() {
    return statutoryDescriptionId;
  }

  public void setStatutoryDescriptionId(String statutoryDescriptionId) {
    this.statutoryDescriptionId = statutoryDescriptionId;
  }

  public Service serviceClasses(List<FintoItem> serviceClasses) {
    this.serviceClasses = serviceClasses;
    return this;
  }

  public Service addServiceClassesItem(FintoItem serviceClassesItem) {
    this.serviceClasses.add(serviceClassesItem);
    return this;
  }

   /**
   * Get serviceClasses
   * @return serviceClasses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getServiceClasses() {
    return serviceClasses;
  }

  public void setServiceClasses(List<FintoItem> serviceClasses) {
    this.serviceClasses = serviceClasses;
  }

  public Service ontologyTerms(List<FintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
    return this;
  }

  public Service addOntologyTermsItem(FintoItem ontologyTermsItem) {
    this.ontologyTerms.add(ontologyTermsItem);
    return this;
  }

   /**
   * Get ontologyTerms
   * @return ontologyTerms
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getOntologyTerms() {
    return ontologyTerms;
  }

  public void setOntologyTerms(List<FintoItem> ontologyTerms) {
    this.ontologyTerms = ontologyTerms;
  }

  public Service targetGroups(List<FintoItem> targetGroups) {
    this.targetGroups = targetGroups;
    return this;
  }

  public Service addTargetGroupsItem(FintoItem targetGroupsItem) {
    this.targetGroups.add(targetGroupsItem);
    return this;
  }

   /**
   * Get targetGroups
   * @return targetGroups
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getTargetGroups() {
    return targetGroups;
  }

  public void setTargetGroups(List<FintoItem> targetGroups) {
    this.targetGroups = targetGroups;
  }

  public Service lifeEvents(List<FintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
    return this;
  }

  public Service addLifeEventsItem(FintoItem lifeEventsItem) {
    this.lifeEvents.add(lifeEventsItem);
    return this;
  }

   /**
   * Get lifeEvents
   * @return lifeEvents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getLifeEvents() {
    return lifeEvents;
  }

  public void setLifeEvents(List<FintoItem> lifeEvents) {
    this.lifeEvents = lifeEvents;
  }

  public Service industrialClasses(List<FintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
    return this;
  }

  public Service addIndustrialClassesItem(FintoItem industrialClassesItem) {
    this.industrialClasses.add(industrialClassesItem);
    return this;
  }

   /**
   * Get industrialClasses
   * @return industrialClasses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<FintoItem> getIndustrialClasses() {
    return industrialClasses;
  }

  public void setIndustrialClasses(List<FintoItem> industrialClasses) {
    this.industrialClasses = industrialClasses;
  }

  public Service names(List<LocalizedListItem> names) {
    this.names = names;
    return this;
  }

  public Service addNamesItem(LocalizedListItem namesItem) {
    this.names.add(namesItem);
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getNames() {
    return names;
  }

  public void setNames(List<LocalizedListItem> names) {
    this.names = names;
  }

  public Service descriptions(List<LocalizedListItem> descriptions) {
    this.descriptions = descriptions;
    return this;
  }

  public Service addDescriptionsItem(LocalizedListItem descriptionsItem) {
    this.descriptions.add(descriptionsItem);
    return this;
  }

   /**
   * Get descriptions
   * @return descriptions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getDescriptions() {
    return descriptions;
  }

  public void setDescriptions(List<LocalizedListItem> descriptions) {
    this.descriptions = descriptions;
  }

  public Service languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public Service addLanguagesItem(String languagesItem) {
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getLanguages() {
    return languages;
  }

  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }

  public Service keywords(List<LanguageItem> keywords) {
    this.keywords = keywords;
    return this;
  }

  public Service addKeywordsItem(LanguageItem keywordsItem) {
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * List of localized service keywords.
   * @return keywords
  **/
  @ApiModelProperty(example = "null", value = "List of localized service keywords.")
  public List<LanguageItem> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<LanguageItem> keywords) {
    this.keywords = keywords;
  }

  public Service legislation(List<Law> legislation) {
    this.legislation = legislation;
    return this;
  }

  public Service addLegislationItem(Law legislationItem) {
    this.legislation.add(legislationItem);
    return this;
  }

   /**
   * List of laws related to the service.
   * @return legislation
  **/
  @ApiModelProperty(example = "null", value = "List of laws related to the service.")
  public List<Law> getLegislation() {
    return legislation;
  }

  public void setLegislation(List<Law> legislation) {
    this.legislation = legislation;
  }

  public Service coverageType(String coverageType) {
    this.coverageType = coverageType;
    return this;
  }

   /**
   * Service coverage type. Valid values are: Local or Nationwide.
   * @return coverageType
  **/
  @ApiModelProperty(example = "null", value = "Service coverage type. Valid values are: Local or Nationwide.")
  public String getCoverageType() {
    return coverageType;
  }

  public void setCoverageType(String coverageType) {
    this.coverageType = coverageType;
  }

  public Service municipalities(List<Municipality> municipalities) {
    this.municipalities = municipalities;
    return this;
  }

  public Service addMunicipalitiesItem(Municipality municipalitiesItem) {
    this.municipalities.add(municipalitiesItem);
    return this;
  }

   /**
   * Get municipalities
   * @return municipalities
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Municipality> getMunicipalities() {
    return municipalities;
  }

  public void setMunicipalities(List<Municipality> municipalities) {
    this.municipalities = municipalities;
  }

  public Service webPages(List<WebPage> webPages) {
    this.webPages = webPages;
    return this;
  }

  public Service addWebPagesItem(WebPage webPagesItem) {
    this.webPages.add(webPagesItem);
    return this;
  }

   /**
   * Get webPages
   * @return webPages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<WebPage> getWebPages() {
    return webPages;
  }

  public void setWebPages(List<WebPage> webPages) {
    this.webPages = webPages;
  }

  public Service requirements(List<LanguageItem> requirements) {
    this.requirements = requirements;
    return this;
  }

  public Service addRequirementsItem(LanguageItem requirementsItem) {
    this.requirements.add(requirementsItem);
    return this;
  }

   /**
   * Get requirements
   * @return requirements
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LanguageItem> getRequirements() {
    return requirements;
  }

  public void setRequirements(List<LanguageItem> requirements) {
    this.requirements = requirements;
  }

  public Service publishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
    return this;
  }

   /**
   * Publishing status. Possible values are: Draft, Published, Deleted, Modified or OldPublished.
   * @return publishingStatus
  **/
  @ApiModelProperty(example = "null", value = "Publishing status. Possible values are: Draft, Published, Deleted, Modified or OldPublished.")
  public String getPublishingStatus() {
    return publishingStatus;
  }

  public void setPublishingStatus(String publishingStatus) {
    this.publishingStatus = publishingStatus;
  }

  public Service chargeType(String chargeType) {
    this.chargeType = chargeType;
    return this;
  }

   /**
   * Get chargeType
   * @return chargeType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getChargeType() {
    return chargeType;
  }

  public void setChargeType(String chargeType) {
    this.chargeType = chargeType;
  }

  public Service additionalInformations(List<LocalizedListItem> additionalInformations) {
    this.additionalInformations = additionalInformations;
    return this;
  }

  public Service addAdditionalInformationsItem(LocalizedListItem additionalInformationsItem) {
    this.additionalInformations.add(additionalInformationsItem);
    return this;
  }

   /**
   * Get additionalInformations
   * @return additionalInformations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LocalizedListItem> getAdditionalInformations() {
    return additionalInformations;
  }

  public void setAdditionalInformations(List<LocalizedListItem> additionalInformations) {
    this.additionalInformations = additionalInformations;
  }

  public Service organizations(List<ServiceOrganization> organizations) {
    this.organizations = organizations;
    return this;
  }

  public Service addOrganizationsItem(ServiceOrganization organizationsItem) {
    this.organizations.add(organizationsItem);
    return this;
  }

   /**
   * Get organizations
   * @return organizations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceOrganization> getOrganizations() {
    return organizations;
  }

  public void setOrganizations(List<ServiceOrganization> organizations) {
    this.organizations = organizations;
  }

  public Service electronicServiceChannels(List<ServiceServiceChannel> electronicServiceChannels) {
    this.electronicServiceChannels = electronicServiceChannels;
    return this;
  }

  public Service addElectronicServiceChannelsItem(ServiceServiceChannel electronicServiceChannelsItem) {
    this.electronicServiceChannels.add(electronicServiceChannelsItem);
    return this;
  }

   /**
   * Get electronicServiceChannels
   * @return electronicServiceChannels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceServiceChannel> getElectronicServiceChannels() {
    return electronicServiceChannels;
  }

  public void setElectronicServiceChannels(List<ServiceServiceChannel> electronicServiceChannels) {
    this.electronicServiceChannels = electronicServiceChannels;
  }

  public Service phoneServiceChannels(List<ServiceServiceChannel> phoneServiceChannels) {
    this.phoneServiceChannels = phoneServiceChannels;
    return this;
  }

  public Service addPhoneServiceChannelsItem(ServiceServiceChannel phoneServiceChannelsItem) {
    this.phoneServiceChannels.add(phoneServiceChannelsItem);
    return this;
  }

   /**
   * Get phoneServiceChannels
   * @return phoneServiceChannels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceServiceChannel> getPhoneServiceChannels() {
    return phoneServiceChannels;
  }

  public void setPhoneServiceChannels(List<ServiceServiceChannel> phoneServiceChannels) {
    this.phoneServiceChannels = phoneServiceChannels;
  }

  public Service printableFormServiceChannels(List<ServiceServiceChannel> printableFormServiceChannels) {
    this.printableFormServiceChannels = printableFormServiceChannels;
    return this;
  }

  public Service addPrintableFormServiceChannelsItem(ServiceServiceChannel printableFormServiceChannelsItem) {
    this.printableFormServiceChannels.add(printableFormServiceChannelsItem);
    return this;
  }

   /**
   * Get printableFormServiceChannels
   * @return printableFormServiceChannels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceServiceChannel> getPrintableFormServiceChannels() {
    return printableFormServiceChannels;
  }

  public void setPrintableFormServiceChannels(List<ServiceServiceChannel> printableFormServiceChannels) {
    this.printableFormServiceChannels = printableFormServiceChannels;
  }

  public Service serviceLocationServiceChannels(List<ServiceServiceChannel> serviceLocationServiceChannels) {
    this.serviceLocationServiceChannels = serviceLocationServiceChannels;
    return this;
  }

  public Service addServiceLocationServiceChannelsItem(ServiceServiceChannel serviceLocationServiceChannelsItem) {
    this.serviceLocationServiceChannels.add(serviceLocationServiceChannelsItem);
    return this;
  }

   /**
   * Get serviceLocationServiceChannels
   * @return serviceLocationServiceChannels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceServiceChannel> getServiceLocationServiceChannels() {
    return serviceLocationServiceChannels;
  }

  public void setServiceLocationServiceChannels(List<ServiceServiceChannel> serviceLocationServiceChannels) {
    this.serviceLocationServiceChannels = serviceLocationServiceChannels;
  }

  public Service webPageServiceChannels(List<ServiceServiceChannel> webPageServiceChannels) {
    this.webPageServiceChannels = webPageServiceChannels;
    return this;
  }

  public Service addWebPageServiceChannelsItem(ServiceServiceChannel webPageServiceChannelsItem) {
    this.webPageServiceChannels.add(webPageServiceChannelsItem);
    return this;
  }

   /**
   * Get webPageServiceChannels
   * @return webPageServiceChannels
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ServiceServiceChannel> getWebPageServiceChannels() {
    return webPageServiceChannels;
  }

  public void setWebPageServiceChannels(List<ServiceServiceChannel> webPageServiceChannels) {
    this.webPageServiceChannels = webPageServiceChannels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.id, service.id) &&
        Objects.equals(this.type, service.type) &&
        Objects.equals(this.statutoryDescriptionId, service.statutoryDescriptionId) &&
        Objects.equals(this.serviceClasses, service.serviceClasses) &&
        Objects.equals(this.ontologyTerms, service.ontologyTerms) &&
        Objects.equals(this.targetGroups, service.targetGroups) &&
        Objects.equals(this.lifeEvents, service.lifeEvents) &&
        Objects.equals(this.industrialClasses, service.industrialClasses) &&
        Objects.equals(this.names, service.names) &&
        Objects.equals(this.descriptions, service.descriptions) &&
        Objects.equals(this.languages, service.languages) &&
        Objects.equals(this.keywords, service.keywords) &&
        Objects.equals(this.legislation, service.legislation) &&
        Objects.equals(this.coverageType, service.coverageType) &&
        Objects.equals(this.municipalities, service.municipalities) &&
        Objects.equals(this.webPages, service.webPages) &&
        Objects.equals(this.requirements, service.requirements) &&
        Objects.equals(this.publishingStatus, service.publishingStatus) &&
        Objects.equals(this.chargeType, service.chargeType) &&
        Objects.equals(this.additionalInformations, service.additionalInformations) &&
        Objects.equals(this.organizations, service.organizations) &&
        Objects.equals(this.electronicServiceChannels, service.electronicServiceChannels) &&
        Objects.equals(this.phoneServiceChannels, service.phoneServiceChannels) &&
        Objects.equals(this.printableFormServiceChannels, service.printableFormServiceChannels) &&
        Objects.equals(this.serviceLocationServiceChannels, service.serviceLocationServiceChannels) &&
        Objects.equals(this.webPageServiceChannels, service.webPageServiceChannels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, statutoryDescriptionId, serviceClasses, ontologyTerms, targetGroups, lifeEvents, industrialClasses, names, descriptions, languages, keywords, legislation, coverageType, municipalities, webPages, requirements, publishingStatus, chargeType, additionalInformations, organizations, electronicServiceChannels, phoneServiceChannels, printableFormServiceChannels, serviceLocationServiceChannels, webPageServiceChannels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    statutoryDescriptionId: ").append(toIndentedString(statutoryDescriptionId)).append("\n");
    sb.append("    serviceClasses: ").append(toIndentedString(serviceClasses)).append("\n");
    sb.append("    ontologyTerms: ").append(toIndentedString(ontologyTerms)).append("\n");
    sb.append("    targetGroups: ").append(toIndentedString(targetGroups)).append("\n");
    sb.append("    lifeEvents: ").append(toIndentedString(lifeEvents)).append("\n");
    sb.append("    industrialClasses: ").append(toIndentedString(industrialClasses)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    legislation: ").append(toIndentedString(legislation)).append("\n");
    sb.append("    coverageType: ").append(toIndentedString(coverageType)).append("\n");
    sb.append("    municipalities: ").append(toIndentedString(municipalities)).append("\n");
    sb.append("    webPages: ").append(toIndentedString(webPages)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    publishingStatus: ").append(toIndentedString(publishingStatus)).append("\n");
    sb.append("    chargeType: ").append(toIndentedString(chargeType)).append("\n");
    sb.append("    additionalInformations: ").append(toIndentedString(additionalInformations)).append("\n");
    sb.append("    organizations: ").append(toIndentedString(organizations)).append("\n");
    sb.append("    electronicServiceChannels: ").append(toIndentedString(electronicServiceChannels)).append("\n");
    sb.append("    phoneServiceChannels: ").append(toIndentedString(phoneServiceChannels)).append("\n");
    sb.append("    printableFormServiceChannels: ").append(toIndentedString(printableFormServiceChannels)).append("\n");
    sb.append("    serviceLocationServiceChannels: ").append(toIndentedString(serviceLocationServiceChannels)).append("\n");
    sb.append("    webPageServiceChannels: ").append(toIndentedString(webPageServiceChannels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

