/**
 * RESTful PTV
 * Restful way to use Palvelutietovaranto.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fi.metatavu.restfulptv.client;

import fi.metatavu.restfulptv.client.model.*;

import fi.metatavu.restfulptv.client.model.BadRequest;
import fi.metatavu.restfulptv.client.model.WebPageChannel;
import fi.metatavu.restfulptv.client.model.Forbidden;
import fi.metatavu.restfulptv.client.model.InternalServerError;
import fi.metatavu.restfulptv.client.model.NotFound;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-09T18:15:52.391+02:00")
public class WebPageChannelsApi {

  private ApiClient client;
  private String baseUrl;

  public WebPageChannelsApi(String baseUrl, ApiClient client) {
    this.client = client;
    this.baseUrl = baseUrl;
  }
  
  /**
   * creates WebPageChannel
   * creates WebPageChannel
   * @param serviceId service id (required)
   * @param body Payload (required)
   */
  public ApiResponse<WebPageChannel> createServiceWebPageChannel(String serviceId, WebPageChannel body) {
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, Object> formParams = new HashMap<>();
        
        
    String path = String.format("%s/services/{serviceId}/webPageChannels"
      .replaceAll("\\{" + "serviceId" + "\\}", String.valueOf(serviceId)), baseUrl);
      
    ResultType<WebPageChannel> resultType = new ResultType<WebPageChannel>() {};
    return client.doPOSTRequest(path, resultType, queryParams, formParams);
  }
  /**
   * finds WebPageChannel by webPageChannelId
   * finds WebPageChannels by webPageChannelId
   * @param serviceId Service id (required)
   * @param webPageChannelId webPageChannel id (required)
   */
  public ApiResponse<WebPageChannel> findServiceWebPageChannel(String serviceId, String webPageChannelId) {
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, Object> formParams = new HashMap<>();
        
        
    String path = String.format("%s/services/{serviceId}/webPageChannels/{webPageChannelId}"
      .replaceAll("\\{" + "serviceId" + "\\}", String.valueOf(serviceId))
      .replaceAll("\\{" + "webPageChannelId" + "\\}", String.valueOf(webPageChannelId)), baseUrl);
      
    ResultType<WebPageChannel> resultType = new ResultType<WebPageChannel>() {};
    return client.doGETRequest(path, resultType, queryParams, formParams);
  }
  /**
   * Lists WebPageChannels by serviceId
   * Lists WebPageChannels by serviceId
   * @param serviceId Service id (required)
   * @param firstResult First result (optional)
   * @param maxResults Max results (optional)
   */
  public ApiResponse<List<WebPageChannel>> listServiceWebPageChannels(String serviceId, Long firstResult, Long maxResults) {
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, Object> formParams = new HashMap<>();
    if (firstResult != null)
    queryParams.put("firstResult", firstResult);
if (maxResults != null)
    queryParams.put("maxResults", maxResults);
    
        
    String path = String.format("%s/services/{serviceId}/webPageChannels"
      .replaceAll("\\{" + "serviceId" + "\\}", String.valueOf(serviceId)), baseUrl);
      
    ResultType<List<WebPageChannel>> resultType = new ResultType<List<WebPageChannel>>() {};
    return client.doGETRequest(path, resultType, queryParams, formParams);
  }
  /**
   * Updates WebPageChannel
   * Updates WebPageChannel
   * @param serviceId service id (required)
   * @param webPageChannelId webPageChannel id (required)
   * @param body Payload (required)
   */
  public ApiResponse<WebPageChannel> updateWebPageChannel(String serviceId, String webPageChannelId, WebPageChannel body) {
    Map<String, Object> queryParams = new HashMap<>();
    Map<String, Object> formParams = new HashMap<>();
        
        
    String path = String.format("%s/services/{serviceId}/webPageChannels/{webPageChannelId}"
      .replaceAll("\\{" + "serviceId" + "\\}", String.valueOf(serviceId))
      .replaceAll("\\{" + "webPageChannelId" + "\\}", String.valueOf(webPageChannelId)), baseUrl);
      
    ResultType<WebPageChannel> resultType = new ResultType<WebPageChannel>() {};
    return client.doPUTRequest(path, resultType, queryParams, formParams);
  }
  
}
